# Change these first
owner: mostlai # Your GitHub organization or username, where this repository lives
repo: mostlai-status # The name of this repository

sites:
  - name: "🏠 Mostlai's Blog"
    url: https://mostlai.github.io/
  - name: "🌏 Mostlai's Hundred-Days"
    url: https://mostlai.github.io/Hundred-days/
  - name: "🌙 Mostlai's HD-TEST"
    url: https://mostlai.github.io/HD-TEST/
  - name: "📖 Mostlai's HD-WIKI"
    url: https://mostlai.github.io/HD-WIKI/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  baseUrl: /mostlai-status
  logoUrl: https://cdn.jsdelivr.net/gh/mostlai/mostlai-cdn@latest/img/socia.png
  name: "Pldada-Mostlai | Status"
  introTitle: "🎉欢迎来到Pldada-Mostlai的monitor页面"
  introMessage: You are now viewing *Pldada-Mostlai's* status page. Based on Github action and [Uptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Abount me
      href: https://mostlai.github.io/
      
  workflowSchedule:
    graphs: "0 */2 * * *"
    responseTime: "0 */2 * * *"
    staticSite: "0 */2 * * *"
    summary: "0 */2 * * *"
    updateTemplate: "0 */2 * * *"
    updates: "0 */2 * * *"
    uptime: "0 */2 * * *"

  commitMessages:
    commitAuthorName: "@Mostlai"
    commitAuthorEmail: "2096358571@qq.com"
  # Upptime also supports notifications, assigning issues, and more
  # See https://upptime.js.org/docs/configuration
  i18n:
    footer: Made with ❤ by [@mostlai](//github.com/mostlai)
